Installment plan
payplug/payplug-php pull request #19
Opened 2018-11-26 09:11 UTC by Dixeat

Hello I add InstallmentPlan resource, I assign @nilleroux to this pull request. I also ping @Aphy and @pierre-pg for their advices.

2018-11-26 09:37 UTC, pierre-pg commented on tests/unit_tests/Resource/InstallmentPlanTest.php
> +        $this->assertTrue($GLOBALS['CURLOPT_POSTFIELDS_DATA'] === array('abort' => true));
Est-ce qu'un `assertEquals ` ne serait pas mieux ici ? (Ou alors ça fait juste un `==` et pas un `===` ?)

2018-11-26 09:37 UTC, pierre-pg commented on tests/unit_tests/Resource/InstallmentPlanTest.php
> +        $this->assertTrue(is_array($GLOBALS['CURLOPT_POSTFIELDS_DATA']));
Ça vaut probablement le coup de rajouter un assert sur la valeur de `$GLOBALS['CURLOPT_POSTFIELDS_DATA']` comme c'est fait dans les tests suivants.

2018-11-26 13:52 UTC, Dixeat commented on tests/unit_tests/Resource/InstallmentPlanTest.php
> +                      'payments' => array()),
Effectivement merci.

2018-11-26 13:52 UTC, Dixeat commented on tests/unit_tests/Resource/InstallmentPlanTest.php
> +        $this->assertTrue($GLOBALS['CURLOPT_POSTFIELDS_DATA'] === array('abort' => true));
Bien vu, corrigé.

2018-11-26 13:53 UTC, Dixeat commented on tests/unit_tests/Resource/InstallmentPlanTest.php
> +        $this->assertTrue(is_array($GLOBALS['CURLOPT_POSTFIELDS_DATA']));
Oui fait !

2018-11-26 13:55 UTC, Dixeat commented on tests/unit_tests/Resource/InstallmentPlanTest.php
> +            'failure'           => array(
Done

2018-11-28 12:30 UTC, Dixeat commented
Up tout à été mis à jour :)

2018-11-28 15:09 UTC, bukkks requested changes

2018-11-28 16:18 UTC, Dixeat commented on lib/Payplug/Resource/InstallmentPlan.php
> +        throw new Payplug\Exception\NotImplementedException(
Je me suis posé la question, on peut prévoir de l'utiliser mais ne pas l'activer mais effectivement ça s'apparente plus à du bruit. Je supprime.

2018-11-28 16:37 UTC, Dixeat commented on lib/Payplug/Resource/InstallmentPlan.php
> +            throw new Payplug\Exception\InvalidInstallmentPlanException(
Très bien pour moi.

2018-11-28 16:40 UTC, Dixeat commented on lib/Payplug/InstallmentPlan.php
> +    	return $installment_plan->abort($payplug);
Done

2018-11-28 16:40 UTC, Dixeat commented on lib/Payplug/Resource/InstallmentPlan.php
> +            array('abort' => true)
Euh j'ai effectivement mis la même chose que côté paiement. J'ai tendance à dire que vu que c'est déjà implémenté dans l'API on pourra jamais le supprimer à part en sortant une V2 et je ne suis pas sur que le jeu en vaille la chandelle.

2018-11-28 16:48 UTC, nilleroux commented on lib/Payplug/Exception/NotImplementedException.php
> +class NotImplementedException extends HttpException
On peut supprimer ce fichier du coup :wink:

2018-11-28 16:51 UTC, Dixeat commented on lib/Payplug/Exception/NotImplementedException.php
> +class NotImplementedException extends HttpException
Absolument.

2018-11-28 16:54 UTC, nilleroux commented on lib/Payplug/Resource/InstallmentPlan.php
> +            array('abort' => true)
Ma suggestion c'est pas de faire une V2 pour ça (ce serait effectivement ridicule). Mais on pourrait : 
- Ne plus ajouter de nouveau `abort` ;
- Supporter `abort` ET `aborted` sur `PATCH payment` (vraisemblablement pour aussi longtemps que la `v1` existera) ;
- Supprimer toute mention d'`abort` dans la doc, en faveur de `aborted`.

Je pense qu'il faut a minima ne pas réitérer une erreur sur une nouvelle ressource.

2018-11-28 17:00 UTC, Dixeat commented on lib/Payplug/Resource/InstallmentPlan.php
> +            array('abort' => true)
J'invoque l'avis de @pierre-pg !

2018-11-29 10:16 UTC, Dixeat commented on lib/Payplug/Resource/InstallmentPlan.php
> +            array('abort' => true)
Fait dans https://github.com/payplug/payplug-php/pull/21.
Je suggère de merger cette MR avec `abort` comme cela, on à le temps de livrer côté API et ce n'est pas bloquant.

2018-11-29 10:29 UTC, bukkks approved these changes

2018-11-29 10:51 UTC, Aphy approved these changes

2018-11-30 09:56 UTC, pierre-pg commented on lib/Payplug/Resource/InstallmentPlan.php
> +                $payments[] = Payment::retrieve($payment_id, $payplug);
On voulait un dictionnaire non ?

2018-11-30 09:57 UTC, pierre-pg commented on lib/Payplug/Resource/InstallmentPlan.php
> +    public static function retrieve($paymentId, Payplug\Payplug $payplug = null)
Idéalement, il faudrait remplacer `$paymentId` par `$installmentPlanId` (comme c'est indiqué dans la doc au-dessus).

2018-11-30 10:01 UTC, pierre-pg commented
En option, est-ce que tu pourrais au passage changer deux liens dans le README :
- https://www.payplug.com/ (après "You can create a PayPlug account at").
- https://docs.payplug.com/api/ (après "Please see").

Merci !

2018-11-30 10:47 UTC, Dixeat commented on lib/Payplug/Resource/InstallmentPlan.php
> +                $payments[] = Payment::retrieve($payment_id, $payplug);
J'avais oublié oui.

2018-11-30 10:51 UTC, Dixeat commented on lib/Payplug/Resource/InstallmentPlan.php
> +    public static function retrieve($paymentId, Payplug\Payplug $payplug = null)
Yes merci.

2018-11-30 10:58 UTC, Dixeat commented
Merci pour les remarques, ça à été mis à jour !

2018-11-30 13:07 UTC, pierre-pg approved these changes

2019-01-16 08:47 UTC, Dixeat commented
On peut merger du coup merci !

2019-01-16 08:48 UTC, merged